-- Pagos a profesores.
--
-- Hasta ahora la plataforma solo sabía de la plata que ENTRA: `invoices` está
-- atada a `enrollments` y es la cartera de los estudiantes. Lo que se le paga a
-- un profesor vivía por fuera, en una hoja aparte que había que reconciliar a
-- mano contra las clases dictadas — que es justamente el dato que solo existe
-- aquí.
--
-- Esto agrega las dos piezas que faltaban: la tarifa acordada con cada profesor
-- en cada cohorte, y el registro de lo que se le ha pagado. Deliberadamente NO
-- reusa `invoices`: mezclar lo que entra con lo que sale rompería la cartera.

/* -------------------------------------------------------------------------- */
/* La tarifa                                                                   */
/* -------------------------------------------------------------------------- */

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'instructor_pay_mode') THEN
    CREATE TYPE public.instructor_pay_mode AS ENUM ('per_session', 'per_cohort', 'monthly');
  END IF;
END $$;

-- En tabla aparte y NO como columnas de `cohort_instructors`: esa tabla tiene
-- una política de lectura pública (los instructores de una cohorte se muestran
-- en el sitio), así que ponerle el monto dejaría el sueldo de cada profesor a
-- la vista de cualquiera.
CREATE TABLE IF NOT EXISTS public.instructor_rates (
  instructor_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cohort_id bigint NOT NULL REFERENCES public.cohorts(id) ON DELETE CASCADE,
  mode public.instructor_pay_mode NOT NULL,
  amount numeric(12, 2) NOT NULL CHECK (amount >= 0),
  -- Una clase entra al pago solo cuando el profesor pasó su lista. Es lo que
  -- mantiene la asistencia al día sin tener que perseguir a nadie.
  requires_attendance boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (instructor_id, cohort_id)
);

COMMENT ON TABLE public.instructor_rates IS
  'Lo acordado con cada profesor en cada cohorte. Separada de cohort_instructors porque esa es de lectura pública.';
COMMENT ON COLUMN public.instructor_rates.mode IS
  'per_session: por clase dictada. per_cohort: un pago al cerrar. monthly: fijo cada mes.';
COMMENT ON COLUMN public.instructor_rates.requires_attendance IS
  'Si es true, una clase solo cuenta para el pago cuando tiene asistencia registrada.';

ALTER TABLE public.instructor_rates ENABLE ROW LEVEL SECURITY;

-- Cada profesor ve su propia tarifa, no la de los demás.
DROP POLICY IF EXISTS "Instructors read own rate" ON public.instructor_rates;
CREATE POLICY "Instructors read own rate"
  ON public.instructor_rates FOR SELECT
  TO authenticated
  USING (instructor_id = auth.uid());

-- Acotada a `authenticated` a propósito: is_admin() está revocada para anon y
-- una política FOR ALL sin TO se evalúa también en los SELECT anónimos.
DROP POLICY IF EXISTS "Admins manage instructor rates" ON public.instructor_rates;
CREATE POLICY "Admins manage instructor rates"
  ON public.instructor_rates FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

/* -------------------------------------------------------------------------- */
/* Los pagos hechos                                                            */
/* -------------------------------------------------------------------------- */

CREATE TABLE IF NOT EXISTS public.instructor_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instructor_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cohort_id bigint NOT NULL REFERENCES public.cohorts(id) ON DELETE CASCADE,
  concept text NOT NULL,
  amount numeric(12, 2) NOT NULL CHECK (amount >= 0),
  -- El periodo que cubre el pago. Para el modo por clase es el mes; para los
  -- otros dos, el tramo que se acordó.
  period_start date NOT NULL,
  period_end date NOT NULL,
  -- Cuántas clases respaldan el monto: es lo que hace auditable la cifra.
  session_count integer NOT NULL DEFAULT 0 CHECK (session_count >= 0),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
  paid_at timestamptz,
  method text,
  notes text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT instructor_payments_period_order CHECK (period_end >= period_start)
);

COMMENT ON TABLE public.instructor_payments IS
  'Lo que se le paga a cada profesor por cohorte y periodo. Registro interno: no genera documento fiscal.';
COMMENT ON COLUMN public.instructor_payments.session_count IS
  'Clases que respaldan el monto, para poder auditar la cifra.';

-- Un pago por profesor, cohorte y periodo: evita pagar dos veces el mismo mes.
CREATE UNIQUE INDEX IF NOT EXISTS instructor_payments_unique_period
  ON public.instructor_payments (instructor_id, cohort_id, period_start, period_end);

CREATE INDEX IF NOT EXISTS instructor_payments_instructor_idx
  ON public.instructor_payments (instructor_id, period_start DESC);
CREATE INDEX IF NOT EXISTS instructor_payments_cohort_idx
  ON public.instructor_payments (cohort_id);
CREATE INDEX IF NOT EXISTS instructor_payments_status_idx
  ON public.instructor_payments (status);

ALTER TABLE public.instructor_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Instructors read own payments" ON public.instructor_payments;
CREATE POLICY "Instructors read own payments"
  ON public.instructor_payments FOR SELECT
  TO authenticated
  USING (instructor_id = auth.uid());

DROP POLICY IF EXISTS "Admins manage instructor payments" ON public.instructor_payments;
CREATE POLICY "Admins manage instructor payments"
  ON public.instructor_payments FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

/* -------------------------------------------------------------------------- */
/* updated_at                                                                  */
/* -------------------------------------------------------------------------- */

CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS instructor_rates_touch_updated_at ON public.instructor_rates;
CREATE TRIGGER instructor_rates_touch_updated_at
  BEFORE UPDATE ON public.instructor_rates
  FOR EACH ROW
  EXECUTE FUNCTION public.touch_updated_at();

DROP TRIGGER IF EXISTS instructor_payments_touch_updated_at ON public.instructor_payments;
CREATE TRIGGER instructor_payments_touch_updated_at
  BEFORE UPDATE ON public.instructor_payments
  FOR EACH ROW
  EXECUTE FUNCTION public.touch_updated_at();
